name: Chrono
favicon: null
layout_spectrum: 0.13552
typography_spectrum: 0.60138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4d4d'
    - '#f7931a'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
